version: '1'
services:
  app:
    build: .
    ports:
      - "1707:1707"
    volumes:
      - ./src/models/ticketDB.json:/usr/src/app/src/models/ticketDB.json
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env

volumes:
  node_modules:
